# Generated by Django 3.0.7 on 2020-11-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApllicationFeatures',
            new_name='ApplicationFeatures',
        ),
    ]
