# Generated by Django 3.0.7 on 2020-11-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201123_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfeatures',
            name='limit_user_signup',
            field=models.BooleanField(default=False),
        ),
    ]
