# Generated by Django 3.0.7 on 2020-11-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_applicationfeatures_limit_user_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfeatures',
            name='signup',
            field=models.BooleanField(default=True),
        ),
    ]
