debug: FALSE
project_name: PYTHON COUCH POTATO
project_sub_name: The Python Couch Potato project
secret_key: THINK CLOCK SMOG FLAG SMACK TINKER FLUNK # enter any random string
advanced_features: True

sql_database: "sqlite:///{cwd}/bookied-local.db"

connection:
    use: hercules # enter your desired chain

    hercules:
        node:
          - wss://hercules.peerplays.download/api 
        nobroadcast: False
        num_retries: 1

    elizabeth:
        node:
          - https://elizabeth.peerplays.download/api
        nobroadcast: False
        num_retries: 1


    alice:
        node:
          - wss://node.peerblock.trade:8090
          - wss://ppyapi.spacemx.tech
          - wss://api-ppy.blckchnd.com
          - wss://pma.blockveritas.co/ws
          - wss://ppyws.roelandp.nl/ws
          - wss://api.eifos.org
          - wss://peerplaysblockchain.net/mainnet/api
          - wss://api.ppy.alex-pu.info
          - wss://api.ppy.blockoperations.com
        nobroadcast: False
        num_retries: 1

    beatrice:
        node:
          - wss://pta.blockveritas.co/ws
          - wss://peerplaysblockchain.net/testnet/api
          - wss://api-ppy-beatrice.blckchnd.com
          - wss://api-beatrice01.eifos.org
          - wss://api-testnet.ppy.alex-pu.info
          - wss://node.testnet.peerblock.trade
          - wss://testnet-ppyapi.spacemx.tech
        nobroadcast: False
        num_retries: 1

allowed_assets:
    - BTFUN
    - PPY
    - TEST
    - BTF

potatoNames:
  - cpx
  - cpy 

bosApis: 
  - http://hercules.peerplays.download:8010/trigger:
    - cpi
    - cp2
  - http://1.hercules.peerplays.download:8010/trigger:
    - cp2
    - j 
  - http://2.hercules.peerplays.download:8010/trigger:
    - cp3
  - http://3.hercules.peerplays.download:8010/trigger:
    - cp4

token:
  - 4013017

token_telegram: '1788336903:AAE_y0beDflEG00-UVABjt4kOH2_XdU3GcI'

telegram_chat_ids:
  - "990772424"
