debug: FALSE
project_name: PYTHON COUCH POTATO
project_sub_name: The Python Couch Potato project
secret_key: THINK CLOCK SMOG FLAG SMACK TINKER FLUNK # enter any random string
advanced_features: True
          
sql_database: "sqlite:///{cwd}/bookied-local.db"

connection:
    use: hercules # enter your desired chain
          
    hercules:
        node:
          - wss://hercules.peerplays.download/api
        nobroadcast: False
        num_retries: 1

allowed_assets:
    - BTFUN
    - PPY
    - TEST
    - BTF
potatoNames:
  - cpx
  - cpy

bosApis:
  - http://hercules.peerplays.download:8010/trigger:
    - cpi
    - cp2

token:
  - 

token_telegram: ''

telegram_chat_ids:
  - ""
 
