debug: FALSE
project_name: PYTHON COUCH POTATO
project_sub_name: The Python Couch Potato project
secret_key: THINK CLOCK SMOG FLAG SMACK TINKER FLUNK # enter any random string
advanced_features: True

sql_database: "sqlite:///{cwd}/bookied-local.db"

connection:
    use: beatrice # enter your desired chain

    alice:
        node:
          - wss://node.peerblock.trade:8090
          - wss://ppyapi.spacemx.tech
          - wss://api-ppy.blckchnd.com
          - wss://pma.blockveritas.co/ws
          - wss://ppyws.roelandp.nl/ws
          - wss://api.eifos.org
          - wss://peerplaysblockchain.net/mainnet/api
          - wss://api.ppy.alex-pu.info
          - wss://api.ppy.blockoperations.com
        nobroadcast: False
        num_retries: 1

    beatrice:
        node:
          - wss://pta.blockveritas.co/ws
          - wss://peerplaysblockchain.net/testnet/api
          - wss://api-ppy-beatrice.blckchnd.com
          - wss://api-beatrice01.eifos.org
          - wss://api-testnet.ppy.alex-pu.info
          - wss://node.testnet.peerblock.trade
          - wss://testnet-ppyapi.spacemx.tech
        nobroadcast: False
        num_retries: 1

allowed_assets:
    - BTFUN
    - PPY
    - TEST
    - BTF

potatoNames:
  - "couchpotato1"

bosApis: 
  - "http://<BOS_AUTO_HOST1>:8010/trigger"
  - "http://<BOS_AUTO_HOST2>:8010/trigger"
