debug: FALSE
project_name: MINT
project_sub_name: The BOS Manual Intervention Module
secret_key: THINK CLOCK SMOG FLAG SMACK TINKER FLUNK # enter any random string
advanced_features: False

sql_database: "sqlite:///{cwd}/bookied-local.db"

dataproxy_link:
    ping_interval_in_seconds: 300

    proxies:

connection:
    use: gladiator # enter your desired chain

    beatrice:
        node:
          - ws://ec2-99-79-98-229.ca-central-1.compute.amazonaws.com:8090
        nobroadcast: False
        num_entries: 1

    elizabeth:
        node:
          - ws://ec2-99-79-98-229.ca-central-1.compute.amazonaws.com:8090
        nobroadcast: False
        num_entries: 1

    hercules:
        node:
            - wss://hercules.peerplays.download/api
        nobroadcast: False
        num_entries: 1


    gladiator:
        node:
            - ws://96.46.49.16:8090
        nobroadcast: False
        num_entries: 1

allowed_assets:
    - BTFUN
    - PPY
    - TEST
    - BTF

potatoNames:
  - "jemshid5"
  - "jemshid6"

bosApis: 
  - "http://96.46.49.1:8010/trigger"
#  - "http://96.46.49.2:8010/trigger"
#  - "http://96.46.49.3:8010/trigger"
#  - "http://96.46.49.4:8010/trigger"
#  - "http://96.46.49.5:8010/trigger"
#  - "http://96.46.49.6:8010/trigger"
#  - "http://96.46.49.7:8010/trigger"
#  - "http://96.46.49.8:8010/trigger"
#  - "http://96.46.49.9:8010/trigger"
#  - "http://96.46.49.10:8010/trigger"
#  - "http://96.46.49.11:8010/trigger"
#  - "http://96.46.49.12:8010/trigger"
#  - "http://96.46.49.13:8010/trigger"
#  - "http://96.46.49.14:8010/trigger"
#  - "http://96.46.49.15:8010/trigger"
#  - "http://96.46.49.16:8010/trigger"
  - "http://35.183.41.242:8010/trigger"
